---

- hosts: "{{ target | default('nowhere') }}"
  tasks:
      - name: Copy {{ pkg }} to {{ ansible_default_ipv4.address }}
        synchronize:
            src: "{{ pkg }}"
            dest: /var/www/html/necklace
            recursive: yes
            delete: yes
            links: yes
            owner: no
            group: no
            perms: yes
